# Schema for the configuration files of the Vartheme BS5.
vartheme_bs5.settings:
  type: theme_settings
  label: "Vartheme BS5 settings"
  mapping:
    # Containers for regions.
    # ----------------------------
    container_header:
      type: text
      label: "Container for Header region"
    container_content:
      type: text
      label: "Container for Content region"
    container_footer:
      type: text
      label: "Container for Footer region"
